/**
* American Standard Code for Information Interchange
* Early printers often lacked graphics ability, it helped computers communicate with one another. It's the computers language
*/
println("  ***");
println ("**   **");
println ("**    **");
println ("**    **         ****"); 
println ("**    **       **   ***");
println ("**   **       *   **   **");
println (" **    *     *  **  ***  **");
println ("  **    *    *  **     **  *");
println ("    ** **  ** **        **");
println ("    **   **  **");
println ("   *           *");
println ("  *             *");
println (" *    0     0    *");
println (" *   (   @   )   *");
println (" *   (__/ (__/   *");
println ("   *     W     *");
println ("     **     **");
println ("       *****");
println ("  ");
println ("  ");
println ("  ");
println ("  ");
println ("  ");
println ("           ||");
println ("           ||");
println ("           ||");
println ("           ||");
println ("           ||");
println ("           ||");
println (".-----------.------.");
println ("|           |      |");
println ("|           |      |");
println ("|           |      |");
println ("|-----------'------|");
println ("| Logitech         |");
println ("|                  |");
println ("|                  |");
println ("|                  |");
println ("|                  |");
println ("|                  |");
println ("`                  '");
println (" `.              ,'");
println ("   |_          _/");
println ("     '-,____,-'");
println ("   ");
println ("   ");
println ("   ");
println ("   ");
println ("          .:'");
println ("      __ :'__");
println ("   .'`__`-'__``.");
println ("  :__________.-'");
println ("  :_________:");
println ("   :_________`-;");
println ("jgs `.__.-.__.'");
println ("  ");
println ("  ");
println ("  ");
println ("  l");
println (" ()()");
println ("()()()");
println (" ()()");
println ("  ()");
